name: Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11,3.12]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        init-shell : bash
        auto-activate-base: false

    - name: Install dependencies
      run: |
            eval "$(micromamba shell hook --shell bash)"
            micromamba create -n myenv python=${{ matrix.python-version }}
            micromamba activate myenv
            micromamba install boost
            pip install uv
            uv pip install numpy cython

    - name: Run tests
      run: |
        eval "$(micromamba shell hook --shell bash)"
        micromamba activate myenv
        pytest
